fix(levm): handle expects
lambdaclass/lambda_ethereum_rust pull request #1109
Opened 2024-11-07 14:08 UTC by JereSalo

**Motivation**

**Description**

Partially Closes #1074

2024-11-11 19:27 UTC, ilitteri requested changes
The PR looks good overall. Left one comment.

2024-11-11 19:27 UTC, ilitteri commented on crates/vm/levm/clippy_delete.txt
Remove this file.

2024-11-11 19:27 UTC, ilitteri commented on crates/vm/levm/src/db.rs
> +            .ok_or(VMError::AccountShouldHaveBeenCached)?
This should be an internal error.

2024-11-12 15:18 UTC, JereSalo commented on crates/vm/levm/src/db.rs
> +            .ok_or(VMError::AccountShouldHaveBeenCached)?
Done!

2024-11-13 14:52 UTC, ilitteri commented on crates/vm/levm/src/vm.rs
The changes to this file doesn't belong to this PR.

2024-11-13 14:57 UTC, JereSalo commented on crates/vm/levm/src/vm.rs
I didn't realize those changes were reverted in `levm_fixes`, I will change it.

2024-11-13 18:09 UTC, JereSalo commented on crates/vm/levm/src/vm.rs
I think I solved it with [this revert](https://github.com/lambdaclass/lambda_ethereum_rust/pull/1109/commits/7b2248f4ef8796fc3fe645c0425b88899357d14f). But tell me if you think there is something else that don't belong here.

2024-11-13 18:57 UTC, ilitteri approved these changes
LGTM

2024-11-13 19:20 UTC, merged